spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_house?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Aa!123456
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  mvc:
   static-path-pattern: /static/**
  profiles:
    active:
  messages:
    basename: internationalization.login


mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.example.demo.entity

---
server:
  port: 8090
  servlet:
    context-path: /cloudDemo

---
server:
  port: 8091
  servlet:
    context-path: /cloudDemo
spring:
  profiles: dev

---
server:
  port: 8092
  servlet:
    context-path: /cloudDemo
spring:
  profiles: prod
---
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#personnel:
#  name: 消防员
#  age: 23
#  gender: 男
#  list:
#    - 1
#    - 2
#    - 3
#  pet:
#    petName: 狗狗
#    type: 阿拉斯加

logging:
  level:
    com.example: trace
  file:
    path: d:/trace
